# Generated by Django 4.2.25 on 2025-12-19 20:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LensAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('addon_type', models.CharField(choices=[('blue_protection', 'Blue UV Protection'), ('photochromic', 'Photochromic'), ('transition_classic', 'Transition Classic'), ('transition_gen_s', 'Transition Gen-S'), ('transition_gen_8', 'Transition Gen-8'), ('tinted', 'Tinted'), ('premium_blue', 'Premium Blue Filtration'), ('index_upgrade', 'Index Upgrade')], max_length=50)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'lenses_addons',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LensCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('single_vision', 'Single-Vision Lenses'), ('progressive_bifocal', 'Progressive & Bifocal Lenses'), ('reading', 'Reading Glasses'), ('non_prescription', 'Without Prescription Lenses')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Lens Categories',
                'db_table': 'lenses_categories',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='LensOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('lens_index', models.DecimalField(decimal_places=2, max_digits=4)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('features', models.JSONField(default=list)),
                ('min_sphere_power', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('max_sphere_power', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('min_cylinder_power', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('max_cylinder_power', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('available_reading_powers', models.JSONField(blank=True, default=list)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lens_options', to='lenses.lenscategory')),
            ],
            options={
                'db_table': 'lenses_options',
                'ordering': ['category', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='SunglassLensOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lens_type', models.CharField(choices=[('regular', 'Regular'), ('essilor', 'Essilor Crizal Easy Pro')], max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lens_index', models.DecimalField(decimal_places=2, default=1.56, max_digits=4)),
                ('features', models.JSONField(default=list)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'lenses_sunglass_options',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='LensOptionAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lens_compatibility', to='lenses.lensaddon')),
                ('lens_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_addons', to='lenses.lensoption')),
            ],
            options={
                'db_table': 'lenses_option_addons',
                'ordering': ['display_order'],
            },
        ),
        migrations.AddIndex(
            model_name='lensaddon',
            index=models.Index(fields=['code'], name='lenses_addo_code_ed028f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lensoptionaddon',
            unique_together={('lens_option', 'addon')},
        ),
        migrations.AddIndex(
            model_name='lensoption',
            index=models.Index(fields=['code'], name='lenses_opti_code_59ab27_idx'),
        ),
        migrations.AddIndex(
            model_name='lensoption',
            index=models.Index(fields=['category', 'is_active'], name='lenses_opti_categor_380343_idx'),
        ),
    ]
