# Generated by Django 4.2.25 on 2026-02-25 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_paymenttransaction_alter_orderitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('job_type', models.CharField(choices=[('in_store', 'In-Store Job'), ('online', 'Online Order'), ('repair', 'Repair / Adjustment'), ('lens_only', 'Lens Replacement Only'), ('contact', 'Contact Lens Order')], default='in_store', max_length=20)),
                ('source', models.CharField(choices=[('walk_in', 'Walk-In'), ('phone', 'Phone'), ('website', 'Website'), ('whatsapp', 'WhatsApp'), ('referral', 'Referral')], default='walk_in', max_length=20)),
                ('status', models.CharField(choices=[('received', 'Job Received'), ('processing', 'In Processing'), ('lens_order', 'Lens Ordered'), ('fitting', 'Frame Fitting'), ('qa', 'Quality Check'), ('ready', 'Ready for Pickup / Dispatch'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered / Collected'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='received', max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('express', 'Express (Same Day)')], default='normal', max_length=10)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_phone', models.CharField(max_length=30)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('re_sphere', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('re_cylinder', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('re_axis', models.IntegerField(blank=True, null=True)),
                ('re_add', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('le_sphere', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('le_cylinder', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('le_axis', models.IntegerField(blank=True, null=True)),
                ('le_add', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('pd_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pd_near', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('frame_description', models.CharField(blank=True, max_length=255)),
                ('lens_brand', models.CharField(blank=True, max_length=100)),
                ('lens_type', models.CharField(blank=True, max_length=100)),
                ('lens_index', models.CharField(blank=True, max_length=20)),
                ('lens_coating', models.CharField(blank=True, max_length=100)),
                ('lens_color', models.CharField(blank=True, max_length=80)),
                ('frame_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lens_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('addon_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('advance_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('promised_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('customer_notes', models.TextField(blank=True)),
                ('prescription_file', models.FileField(blank=True, null=True, upload_to='jobs/prescriptions/%Y/%m/')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_orders', to=settings.AUTH_USER_MODEL)),
                ('linked_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_orders', to='orders.order')),
            ],
            options={
                'verbose_name': 'Job Order',
                'verbose_name_plural': 'Job Orders',
                'db_table': 'jobs_job_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='jobs.joborder')),
            ],
            options={
                'db_table': 'jobs_status_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('prescription', 'Prescription'), ('photo', 'Photo'), ('receipt', 'Receipt'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(upload_to='jobs/documents/%Y/%m/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='jobs.joborder')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs_documents',
            },
        ),
    ]
