# Generated by Django 4.2.25 on 2025-12-15 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('reserved', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('power', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.contactlenspower')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='catalog.productvariant')),
            ],
            options={
                'indexes': [models.Index(fields=['variant', 'power'], name='inventory_s_variant_ca4107_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('variant', 'power'), name='unique_stock_variant_power'),
        ),
    ]
