"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config
SECRET_KEY = config("SECRET_KEY")
DEBUG = config("DEBUG", cast=bool)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
 
ALLOWED_HOSTS = []

# Custom settings
INSTALLED_APPS = [
    # Django core
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

 
    'users',

    # Admin/dashboard
    'adminpanel',

 
    'catalog',
    'content',
    'inventory',
    'lenses',
    'store',
    'cart',
    'orders',
    'prescriptions',
    'reviews',
    'core',
    'notifications',
    'promotions',
    'search',
    'chat_support',
    'wishlist', 
    
]




MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST"),
        "PORT": config("DB_PORT"),
        "OPTIONS": {
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'"
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True



STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

 

# Static files (CSS, JavaScript, Images)
# STATIC_URL = "/static/"
# STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"


MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



SITE_ID = 1

# Django REST Framework configuration
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
}


 
AUTH_USER_MODEL = 'users.User'
# settings.py

LOGIN_URL = '/users/login/'
LOGIN_REDIRECT_URL = '/users/dashboard/'
LOGOUT_REDIRECT_URL = '/users/login/'


#Setting Email

from decouple import config

SECRET_KEY = config("SECRET_KEY")
DEBUG = config("DEBUG", cast=bool)

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587

EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER









# # Add to your settings.py

# # ============================================
# # PAYMENT GATEWAY SETTINGS
# # ============================================

# # Stripe Configuration
# STRIPE_PUBLISHABLE_KEY = 'pk_test_your_publishable_key_here'
# STRIPE_SECRET_KEY = 'sk_test_your_secret_key_here'

# # Razorpay Configuration (Popular in India/Middle East)
# RAZORPAY_KEY_ID = 'rzp_test_your_key_id_here'
# RAZORPAY_KEY_SECRET = 'your_secret_key_here'

# # PayPal Configuration
# PAYPAL_MODE = 'sandbox'  # Change to 'live' for production
# PAYPAL_CLIENT_ID = 'your_client_id_here'
# PAYPAL_CLIENT_SECRET = 'your_client_secret_here'

# # ============================================
# # REQUIRED PACKAGES
# # ============================================
# # Add these to your requirements.txt:
# #
# # stripe>=5.0.0
# # razorpay>=1.3.0
# # paypalrestsdk>=1.13.1

# # ============================================
# # INSTALLATION COMMANDS
# # ============================================
# # pip install stripe razorpay paypalrestsdk



USE_I18N = True

LANGUAGES = [
    ('en', 'English'),
    ('ar', 'Arabic'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]


# Language switcher URLs
LANGUAGE_COOKIE_NAME = 'django_language'
LANGUAGE_COOKIE_AGE = 31536000  # 1 year



# ══════════════════════════════════════════════════════════════
# ADD TO settings.py  — Sadad (Qatar) Payment Gateway
# ══════════════════════════════════════════════════════════════

# ── Sadad ─────────────────────────────────────────────────────
# Get these from: https://panel.sadad.qa → Integration Settings
SADAD_MERCHANT_ID = "YOUR_MERCHANT_ID"         
SADAD_API_KEY     = "YOUR_API_KEY"              
SADAD_SECRET_KEY  = "YOUR_SECRET_KEY"            

# Switch to production URL when ready:
SADAD_BASE_URL    = "https://api-gateway-sandbox.sadad.qa"   
# SADAD_BASE_URL  = "https://api-gateway.sadad.qa"         

SADAD_RETURN_URL  = "https://yoursite.com/orders/payment/sadad/return/"

# ── Stripe ────────────────────────────────────────────────────
STRIPE_SECRET_KEY      = "sk_test_..."
STRIPE_PUBLISHABLE_KEY = "pk_test_..."

# ── Razorpay ──────────────────────────────────────────────────
RAZORPAY_KEY_ID     = "rzp_test_..."
RAZORPAY_KEY_SECRET = "..."

# ── PayPal ────────────────────────────────────────────────────
PAYPAL_MODE          = "sandbox"    
PAYPAL_CLIENT_ID     = "..."
PAYPAL_CLIENT_SECRET = "..."

 
