# Generated by Django 4.2.25 on 2025-12-15 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_sphere', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('right_sphere', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('left_cyl', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('right_cyl', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('left_axis', models.IntegerField(blank=True, null=True)),
                ('right_axis', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='prescriptions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
