# Generated by Django 4.2.25 on 2025-12-19 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_type', models.CharField(choices=[('eyeglasses', 'Eyeglasses'), ('contact_lenses', 'Contact Lenses'), ('reading', 'Reading Glasses')], max_length=50)),
                ('prescription_name', models.CharField(blank=True, max_length=200)),
                ('od_sphere', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('od_cylinder', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('od_axis', models.IntegerField(blank=True, null=True)),
                ('od_add', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('os_sphere', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('os_cylinder', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('os_axis', models.IntegerField(blank=True, null=True)),
                ('os_add', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('pd', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('pd_left', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('pd_right', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('od_base_curve', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('os_base_curve', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('od_diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('os_diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('prescription_file', models.FileField(blank=True, null=True, upload_to='prescriptions/')),
                ('doctor_name', models.CharField(blank=True, max_length=200)),
                ('clinic_name', models.CharField(blank=True, max_length=200)),
                ('prescription_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prescriptions',
                'ordering': ['-is_default', '-created_at'],
                'indexes': [models.Index(fields=['customer', '-created_at'], name='prescriptio_custome_cc7455_idx'), models.Index(fields=['customer', 'is_default'], name='prescriptio_custome_626f04_idx')],
            },
        ),
    ]
