# Generated by Django 4.2.25 on 2025-12-15 14:03

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160)),
                ('type', models.CharField(blank=True, choices=[('sunglass', 'Sunglass'), ('eyeglass', 'Eyeglass'), ('contact_lens', 'Contact Lens')], max_length=30, null=True)),
                ('active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category')),
            ],
        ),
        migrations.CreateModel(
            name='ContactLensPower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5, unique=True)),
                ('is_plano', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LensOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('provider', models.CharField(blank=True, max_length=150)),
                ('index', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('features', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=270, unique=True)),
                ('description', models.TextField(blank=True)),
                ('product_type', models.CharField(choices=[('sunglass', 'Sunglass'), ('eyeglass', 'Eyeglass'), ('contact_lens', 'Contact Lens')], max_length=30)),
                ('has_power', models.BooleanField(default=False)),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=120, null=True)),
                ('color_name', models.CharField(max_length=120)),
                ('color_code', models.CharField(blank=True, max_length=20, null=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('is_power_allowed', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='LensRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_plano', models.BooleanField(default=True)),
                ('allow_power', models.BooleanField(default=False)),
                ('power_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('power_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('note', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lens_rules', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='LensPowerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=False)),
                ('is_special_order', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
                ('power', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.contactlenspower')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_availabilities', to='catalog.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='LensAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('lens_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='catalog.lensoption')),
            ],
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'color_name'], name='catalog_pro_product_5b9c8c_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'color_name'), name='unique_product_color'),
        ),
        migrations.AddIndex(
            model_name='lenspoweravailability',
            index=models.Index(fields=['variant', 'power'], name='catalog_len_variant_214d6c_idx'),
        ),
        migrations.AddConstraint(
            model_name='lenspoweravailability',
            constraint=models.UniqueConstraint(fields=('variant', 'power'), name='unique_variant_power'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('slug', 'parent'), name='unique_category_slug_parent'),
        ),
    ]
