# Generated by Django 4.2.25 on 2025-12-19 09:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(upload_to='brands/')),
                ('description', models.TextField(blank=True)),
                ('available_for_sunglasses', models.BooleanField(default=False)),
                ('available_for_eyeglasses', models.BooleanField(default=False)),
                ('available_for_kids', models.BooleanField(default=False)),
                ('available_for_contact_lenses', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'catalog_brands',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product_type', models.CharField(choices=[('sunglasses', 'Sunglasses'), ('eyeglasses', 'Eyeglasses'), ('contact_lenses', 'Contact Lenses'), ('accessories', 'Accessories'), ('reading_glasses', 'Reading Glasses')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'catalog_categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('product_type', models.CharField(choices=[('sunglasses', 'Sunglasses'), ('eyeglasses', 'Eyeglasses'), ('contact_lenses', 'Contact Lenses'), ('accessories', 'Accessories'), ('reading_glasses', 'Reading Glasses')], db_index=True, max_length=50)),
                ('short_description', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gender', models.CharField(choices=[('unisex', 'Unisex'), ('men', 'Men'), ('women', 'Women'), ('kids', 'Kids')], default='unisex', max_length=20)),
                ('age_group', models.CharField(choices=[('adult', 'Adult'), ('kids', 'Kids')], default='adult', max_length=20)),
                ('track_inventory', models.BooleanField(default=True)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('low_stock_threshold', models.IntegerField(default=5)),
                ('allow_backorder', models.BooleanField(default=False)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_on_sale', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('sales_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'db_table': 'catalog_products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'db_table': 'catalog_product_tags',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_sku', models.CharField(db_index=True, max_length=100, unique=True)),
                ('color_name', models.CharField(blank=True, max_length=100)),
                ('color_code', models.CharField(blank=True, max_length=20)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('lens_width', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bridge_width', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temple_length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
            options={
                'db_table': 'catalog_product_variants',
                'ordering': ['is_default', 'color_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tags', to='catalog.product')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_products', to='catalog.producttag')),
            ],
            options={
                'db_table': 'catalog_product_tag_relations',
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_key', models.CharField(max_length=100)),
                ('spec_value', models.CharField(max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='catalog.product')),
            ],
            options={
                'db_table': 'catalog_product_specifications',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.productvariant')),
            ],
            options={
                'db_table': 'catalog_product_images',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ContactLensProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lens_type', models.CharField(choices=[('clear', 'Clear'), ('color', 'Color')], max_length=20)),
                ('replacement_schedule', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('3_months', 'Up to 3 Months')], max_length=20)),
                ('package_size', models.IntegerField(default=2)),
                ('diameter', models.DecimalField(decimal_places=2, max_digits=4)),
                ('base_curve', models.DecimalField(decimal_places=1, max_digits=3)),
                ('water_content', models.DecimalField(decimal_places=1, max_digits=4)),
                ('power_available', models.BooleanField(default=True)),
                ('min_power', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('max_power', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('color_name', models.CharField(blank=True, max_length=100)),
                ('color_image', models.ImageField(blank=True, null=True, upload_to='contact_lenses/colors/')),
                ('intended_use', models.CharField(default='Vision Correction', max_length=100)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_lens_details', to='catalog.product')),
            ],
            options={
                'db_table': 'catalog_contact_lens_products',
            },
        ),
        migrations.CreateModel(
            name='ContactLensPowerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_value', models.DecimalField(decimal_places=2, max_digits=4)),
                ('is_available', models.BooleanField(default=True)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('contact_lens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_options', to='catalog.contactlensproduct')),
            ],
            options={
                'db_table': 'catalog_contact_lens_power_options',
                'ordering': ['power_value'],
            },
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['slug'], name='catalog_bra_slug_42a137_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['is_active'], name='catalog_bra_is_acti_0bb8e3_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['variant_sku'], name='catalog_pro_variant_f33249_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'is_active'], name='catalog_pro_product_452e85_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'color_name', 'size')},
        ),
        migrations.AlterUniqueTogether(
            name='producttagrelation',
            unique_together={('product', 'tag')},
        ),
        migrations.AddIndex(
            model_name='productspecification',
            index=models.Index(fields=['product'], name='catalog_pro_product_2cc608_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'display_order'], name='catalog_pro_product_172d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='catalog_pro_sku_d0f3e9_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='catalog_pro_slug_60e7f7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type', 'is_active'], name='catalog_pro_product_938652_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'is_active'], name='catalog_pro_brand_i_29c3cc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured', 'is_active'], name='catalog_pro_is_feat_7e4201_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='catalog_pro_created_ae7028_idx'),
        ),
        migrations.AddIndex(
            model_name='contactlensproduct',
            index=models.Index(fields=['lens_type', 'replacement_schedule'], name='catalog_con_lens_ty_4e3b8b_idx'),
        ),
        migrations.AddIndex(
            model_name='contactlenspoweroption',
            index=models.Index(fields=['contact_lens', 'is_available'], name='catalog_con_contact_cd3ec3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contactlenspoweroption',
            unique_together={('contact_lens', 'power_value')},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='catalog_cat_slug_560b25_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['product_type', 'is_active'], name='catalog_cat_product_3c5d73_idx'),
        ),
    ]
