# Generated by Django 4.2.25 on 2025-12-26 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLensColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='contact_lenses/colors/')),
                ('is_active', models.BooleanField(default=True)),
                ('power_enabled', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'catalog_contact_lens_colors',
            },
        ),
        migrations.CreateModel(
            name='LensBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LensOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=10)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_power', models.DecimalField(decimal_places=2, max_digits=4)),
                ('max_power', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'catalog_lens_options',
            },
        ),
        migrations.CreateModel(
            name='LensType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('requires_power', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='contactlenspoweroption',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='brand',
            name='catalog_bra_slug_42a137_idx',
        ),
        migrations.RemoveIndex(
            model_name='brand',
            name='catalog_bra_is_acti_0bb8e3_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='catalog_cat_slug_560b25_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='catalog_cat_product_3c5d73_idx',
        ),
        migrations.RemoveIndex(
            model_name='contactlenspoweroption',
            name='catalog_con_contact_cd3ec3_idx',
        ),
        migrations.RemoveIndex(
            model_name='contactlensproduct',
            name='catalog_con_lens_ty_4e3b8b_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_sku_d0f3e9_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_slug_60e7f7_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_product_938652_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_brand_i_29c3cc_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_is_feat_7e4201_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_pro_created_ae7028_idx',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='catalog_pro_variant_f33249_idx',
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='catalog_pro_product_452e85_idx',
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='brand',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='contactlensproduct',
            name='color_image',
        ),
        migrations.RemoveField(
            model_name='contactlensproduct',
            name='color_name',
        ),
        migrations.RemoveField(
            model_name='contactlensproduct',
            name='max_power',
        ),
        migrations.RemoveField(
            model_name='contactlensproduct',
            name='min_power',
        ),
        migrations.RemoveField(
            model_name='contactlensproduct',
            name='power_available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='allow_backorder',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_on_sale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='low_stock_threshold',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sales_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='views_count',
        ),
        migrations.AddField(
            model_name='category',
            name='has_color_variants',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='has_lens_selection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='has_power',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='has_prescription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='has_size_variants',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contactlensproduct',
            name='intended_use',
            field=models.CharField(default='Vision / Cosmetic', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactlensproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_lens', to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('sunglasses', 'Sunglasses'), ('eyeglasses', 'Eyeglasses'), ('contact_lenses', 'Contact Lenses'), ('accessories', 'Accessories'), ('reading_glasses', 'Reading Glasses')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variant_sku',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='lensoption',
            name='lens_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.lensbrand'),
        ),
        migrations.AddField(
            model_name='lensoption',
            name='lens_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.lenstype'),
        ),
        migrations.AddField(
            model_name='contactlenscolor',
            name='contact_lens',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='catalog.contactlensproduct'),
        ),
        migrations.AlterUniqueTogether(
            name='contactlenspoweroption',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='contactlenspoweroption',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='power_options', to='catalog.contactlenscolor'),
        ),
        migrations.AlterUniqueTogether(
            name='contactlenspoweroption',
            unique_together={('color', 'power_value')},
        ),
        migrations.RemoveField(
            model_name='contactlenspoweroption',
            name='contact_lens',
        ),
    ]
