# Generated by Django 4.2.25 on 2026-02-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_contactlenscolor_lensbrand_lensoption_lenstype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='available_for_accessories',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='available_for_medical_lenses',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='available_for_reading_glasses',
            field=models.BooleanField(default=False),
        ),
    ]
