# Generated by Django 4.2.25 on 2026-02-13 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_support', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatquickreply',
            options={'ordering': ['-usage_count', 'title']},
        ),
        migrations.AddField(
            model_name='chatquickreply',
            name='shortcut',
            field=models.CharField(blank=True, help_text='e.g. /greeting', max_length=30),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting', 'Waiting for Customer'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
