# Generated by Django 4.2.25 on 2025-12-19 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'content_pages',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='StoreLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('google_maps_url', models.URLField(blank=True)),
                ('operating_hours', models.JSONField(default=dict)),
                ('offers_eye_test', models.BooleanField(default=False)),
                ('is_flagship', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'content_store_locations',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('banner_type', models.CharField(choices=[('homepage', 'Homepage'), ('category', 'Category'), ('promotional', 'Promotional')], max_length=50)),
                ('placement', models.CharField(choices=[('main_slider', 'Main Slider'), ('secondary', 'Secondary Banner'), ('sidebar', 'Sidebar')], max_length=50)),
                ('image_desktop', models.ImageField(upload_to='banners/desktop/')),
                ('image_mobile', models.ImageField(blank=True, null=True, upload_to='banners/mobile/')),
                ('image_tablet', models.ImageField(blank=True, null=True, upload_to='banners/tablet/')),
                ('link_url', models.URLField(blank=True)),
                ('link_type', models.CharField(blank=True, choices=[('product', 'Product'), ('category', 'Category'), ('brand', 'Brand'), ('page', 'Page'), ('external', 'External')], max_length=50)),
                ('linked_product_id', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_slide', models.BooleanField(default=True)),
                ('slide_duration', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'content_banners',
                'ordering': ['placement', 'display_order'],
                'indexes': [models.Index(fields=['banner_type', 'is_active'], name='content_ban_banner__4a6fa7_idx'), models.Index(fields=['placement', 'display_order'], name='content_ban_placeme_004d60_idx')],
            },
        ),
        migrations.CreateModel(
            name='EyeTestBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eye_test_bookings', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eye_test_bookings', to='content.storelocation')),
            ],
            options={
                'db_table': 'content_eye_test_bookings',
                'ordering': ['-booking_date', '-booking_time'],
                'indexes': [models.Index(fields=['customer', '-booking_date'], name='content_eye_custome_0b56cf_idx'), models.Index(fields=['location', 'booking_date'], name='content_eye_locatio_e5827e_idx'), models.Index(fields=['status'], name='content_eye_status_7e6c3c_idx')],
            },
        ),
    ]
