# Generated by Django 4.2.25 on 2026-02-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='cta_text',
            field=models.CharField(blank=True, default='Read More', max_length=80),
        ),
        migrations.AddField(
            model_name='banner',
            name='slide_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='slide_heading',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
