# Generated by Django 4.2.25 on 2026-02-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_banner_cta_text_banner_slide_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='placement',
            field=models.CharField(choices=[('main_slider', 'Main Slider'), ('secondary', 'Secondary Banner'), ('sidebar', 'Sidebar'), ('sale_banner', 'Sale Banner (Homepage)')], max_length=50),
        ),
    ]
